### ISSUE TITLE
Enriching the use cases

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#30]
# About

We should enrich our use cases.

## TODO

- [x] Make the existing use cases more clear.
- [x] Add missing use cases.

**Comment by smddzcy** [comment]
@mtoygar @mehmetcalim @OnurOrhan I think we should finish this before our sequence diagram.

**Comment by smddzcy** [comment]
@mtoygar @mehmetcalim @OnurOrhan Any progress?

**Comment by OnurOrhan** [comment]
If you have any ideas for new use cases or details, I'm open to suggestions.

**Comment by smddzcy** [comment]
@OnurOrhan I think we should include updates and removals of events, groups, content etc. Can you please check the new class diagram and (if @gokceuludogan is finished) the new use case diagram? You should notice that there are many missing use cases.

**Comment by gokceuludogan** [comment]
@OnurOrhan I have posted the new version of use case diagram to #38 and also changed it on the use cases page

**Comment by smddzcy** [comment]
@mtoygar @mehmetcalim @OnurOrhan We can assign someone else if you don't have time to do it 😅

**Comment by mtoygar** [comment]
I will add sending invitations to a group/event, removal of the content/event/group/tags/annotations, email verification and banning a user.

I need comment about adding the updates of the content/event/group/tags/annotations since we didn't mention about them in the use case diagram although we have mentioned about the in the class diagram. By the way, sorry for the late response, I was a bit busy in the past week. I hope I will compansate it.

**Comment by mtoygar** [comment]
I decide not to include email verification to the use cases. Because I thought that it is a service, rather than a use case. If you have comments please dont hesitate to share it.

**Comment by mtoygar** [comment]
I have added 3 use cases (use case 10-11-12). 
https://github.com/bounswe/bounswe2017group3/wiki/Use-Cases

**Comment by smddzcy** [comment]
Removing content and inviting users were the most important ones. Thanks @mtoygar 👍 Closing.
