### ISSUE TITLE
Create a sequence diagram for Use Case 4: creating a group page

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group3#47]
## About

**Related Issues:** #30 

We have to create sequence diagrams for our use cases and I am assigned to create a sequence diagram for  [Use Case 4](https://github.com/bounswe/bounswe2017group3/wiki/Use-Cases#use-case-4) about creating a group 

## To-do

- [x] Create a sequence diagram for creating a group

**Comment by gokceuludogan** [comment]
Here the draft of sequence diagram is:
![create group sequence 2](https://cloud.githubusercontent.com/assets/9639399/23874378/13ad9a3e-083e-11e7-88b3-15cdc7b0d369.png)

**Comment by smddzcy** [comment]
Here is my review:

1. `createGroup` is a method of `User`, so I think the receiver should be `User` instead of `Group`.
2. `add group to database` is implicit in our class diagram (we thought it's the job of the DBMS & ORM we'll use and we deliberately made it implicit), so I think you should remove the database parts.
3. I think you should show the instantiation of `group` in `createGroup(group: Group)`. Take a look at this StackOverflow post if you don't know how to show object instantiation: http://stackoverflow.com/questions/2127875/how-do-you-show-instantiation-in-a-uml-sequence-diagram
> Create message on a sequence diagram http://i.msdn.microsoft.com/Dd409377.UML_Sequence(en-us,VS.100).png
  UML Sequence Diagrams: Reference at http://msdn.microsoft.com/en-us/library/dd409377%28VS.100%29.aspx
4. On the `inviteMember(user: User)` part, where the `user` instance comes from is ambiguous. You can get the instance from `System` class and make it explicit. `System` class will implicitly talk with the database (job of DBMS) and get you an `User` instance (job of ORM). In the programmatic syntax:
```java
// Assume you get the user id from user interface.
User user = System.getUserById("xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx");
```

---

I'm totally not an expert on UML, so we could be doing something very wrong, but these are the things that seems missing and that make sense to me 😄

**Comment by gokceuludogan** [comment]
You are right. I have changed it based on your comments. However, the changes might not be done correctly since I am still confused. Here is the new version:
![create group sequence 3](https://cloud.githubusercontent.com/assets/9639399/23877585/a8c62d90-084b-11e7-8947-fab3869cdae7.png)
Another review would be helpful @smddzcy

**Comment by smddzcy** [comment]
Here we see the missing thing in our class diagram 😄  We should call `inviteMember` on `Group` from `UserInterface`, and then `Group` can get the `User` from `System`.

I've added a `inviteMember(userID: UUID): bool` method to `Group` class 👍 

A minor thing: We've called it `User Interface`, there is a space in-between. One of us should change it for consistency 😄

**Comment by gokceuludogan** [comment]
Since we have changed our class diagram, I have edited the sequence diagram. Here it is: 
![create group sequence 5](https://cloud.githubusercontent.com/assets/9639399/23903383/10dfafec-08cd-11e7-8b75-c8f2ab2fbe5e.png)

**Comment by smddzcy** [comment]
I think it's good 👍

**Comment by gokceuludogan** [comment]
OK then I am going to add this to the wiki and close this issue.
